#!/usr/bin/env bash
#
# init-vault.sh — bootstrap a typed-todo vault.
#
# Usage: init-vault.sh [VAULT_PATH] [--git]
#   - VAULT_PATH defaults to $TYPED_TODO_VAULT or $HOME/todo
#   - --git: also `git init` the vault so it can be pushed as its own repo
#   - Idempotent: existing files are never overwritten.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"

VAULT=""
DO_GIT=0
for arg in "$@"; do
  case "$arg" in
    --git) DO_GIT=1 ;;
    -*) echo "unknown flag: $arg" >&2; exit 2 ;;
    *) VAULT="$arg" ;;
  esac
done
VAULT="${VAULT:-${TYPED_TODO_VAULT:-$HOME/todo}}"

mkdir -p "$VAULT"/{tasks,projects,areas,people,resources}

# Copy the ontology spec from the skill into the vault as a reference.
if [ ! -f "$VAULT/ontology.md" ]; then
  if [ -f "$SKILL_DIR/ontology.md" ]; then
    cp "$SKILL_DIR/ontology.md" "$VAULT/ontology.md"
  else
    echo "warning: $SKILL_DIR/ontology.md not found; vault has no spec copy" >&2
  fi
fi

# Seed the inbox.
if [ ! -f "$VAULT/inbox.md" ]; then
  cat > "$VAULT/inbox.md" <<'EOF'
# Inbox

Quick-capture buffer for items not yet structured into Task nodes.
Each line should look like:

- [ ] (t-YYYY-MMDD-NN | unassigned) <description>

IDs are reserved at capture time so promoted Tasks keep their identity.
Triage during weekly review.
EOF
fi

# Seed an OVERVIEW.md stub (regenerated by render-overview.py).
if [ ! -f "$VAULT/OVERVIEW.md" ]; then
  cat > "$VAULT/OVERVIEW.md" <<'EOF'
# Overview

_Not generated yet._

Run the renderer to compile this dashboard from the task graph:

```bash
python3 <skill-dir>/scripts/render-overview.py
```
EOF
fi

# Seed a minimal vault README.
if [ ! -f "$VAULT/README.md" ]; then
  cat > "$VAULT/README.md" <<'EOF'
# typed-todo vault

A personal task vault structured as a typed property graph.
See [`ontology.md`](./ontology.md) for the formal spec, and
[`OVERVIEW.md`](./OVERVIEW.md) for the current human-readable dashboard.

## Two views

- **Raw graph** (for the machine): `tasks/`, `projects/`, `areas/`,
  `people/`, `resources/` — one markdown node per file, YAML frontmatter.
- **OVERVIEW.md** (for humans): a generated dashboard. Re-render after edits;
  never hand-edit it.

Operate this vault via the `typed-todo` Claude Code skill, or by hand in any
editor — the format is plain markdown.
EOF
fi

# Optional: make the vault its own git repo for publishing.
if [ "$DO_GIT" -eq 1 ]; then
  if [ ! -d "$VAULT/.git" ]; then
    git -C "$VAULT" init -q -b main
    cat > "$VAULT/.gitignore" <<'EOF'
# Derived/ephemeral artifacts — never the source of truth.
dist/
*.ttl
.DS_Store
EOF
    echo "Initialized git repo at $VAULT (branch main)."
    echo "  Next: create a GitHub repo and push, e.g."
    echo "    gh repo create <name> --private --source=\"$VAULT\" --push"
  else
    echo "git repo already present at $VAULT; left as-is."
  fi
fi

echo "Vault ready at $VAULT"
echo
echo "Layout:"
find "$VAULT" -maxdepth 2 -mindepth 1 -name .git -prune -o \( -type d -o -type f \) -print \
  | sort \
  | sed "s|$VAULT|  .|"
